import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Navbar from './components/Navbar';
import './globals.css';
import Drawer from './components/Drawer';
import Footer from './components/Footer';
import ResponsiveNavbar from './components/ResponsiveNavbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'GKI TC',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Drawer /> */}
        <ResponsiveNavbar>{children}</ResponsiveNavbar>
        <Footer />
      </body>
    </html>
  );
}
